### ISSUE TITLE
setting.set should return a Boolean

### ISSUE THREAD

**Issue by LordMidas** [MSUTeam/MSU#137]
Return `true` if the setting was successfully changed and `false` if it wasn't (e.g. when the setting is locked).

**Comment by TaroEld** [comment]
Should it return false also if the value didn't actually change?

**Comment by LordMidas** [comment]
> Should it return false also if the value didn't actually change?

I thought about this. I think the answer is no. Because we make it so that a return of true means the setting has the value you wanted to set it to and false means it doesn't. As there are no dependency side effects of setting the value when it already has the same value, this setup should be fine.

**Comment by Enduriel** [comment]
I agree with Midas here and someone should probably just write this up because this is quite simple.

**Comment by LordMidas** [comment]
> I agree with Midas here and someone should probably just write this up because this is quite simple.

Already written on my settings-tweaks branch.

**Comment by LordMidas** [comment]
This is has been implemented as of 5b4ee95d7450eceef4962677ef52271aaed9845e. Closing issue.
