### ISSUE TITLE
[BUG] ItemTypes added via the addNewItemType function get sorted at the top of the inventory window

### ISSUE THREAD

**Issue by LordMidas** [MSUTeam/MSU#152]
**Versions**
 - Game: [e.g. 1.5.0.11]
 - MSU: [e.g. 1.0.5]

**Describe the bug**
This is not a problem with our function, rather it also happens when you add new ItemTypes directly at the bottom of the ::Const.ItemType table. deDarxo was able to fix the sorting by adding an ItemType towards the top end of the table rather than at the bottom. Perhaps we should rework our functions so they add the stuff at the top end? Or we figure out what is causing the sorting problem and fix that.

Example:
This bug is causing Flails which are tagged as Cultist item to be sorted at the top of the inventory in Legends. That bug goes away if Cultist is added manually to the ItemType table towards the top end of the table (and push all values down by multiplying them with 2).

**Comment by Enduriel** [comment]
I mean the issue here is that the vanilla sorting algorithm is weird.
```squirrel
if (_item1 == null && _item2 == null)
{
	return 0;
}
else if (_item1 == null && _item2 != null)
{
	return 1;
}
else if (_item1 != null && _item2 == null)
{
	return -1;
}
else if (_item1.getItemType() > _item2.getItemType())
{
	return -1;
}
else if (_item1.getItemType() < _item2.getItemType())
{
	return 1;
}
else if (_item1.getCategories() > _item2.getCategories())
{
	return -1;
}
else if (_item1.getCategories() < _item2.getCategories())
{
	return 1;
}
else if (_item1.getID() > _item2.getID())
{
	return -1;
}
else if (_item1.getID() < _item2.getID())
{
	return 1;
}
else
{
	return 0;
}
```
and it means that when we add a new ItemType it'll have the greatest value of all other ItemTypes, which means it'll affect sorting more than all the other itemtypes. Unfortunately this can only be solved by adding stuff to the bottom of the list, but even this still breaks sorting by Categories and IDs :/
