### ISSUE TITLE
[REQUEST] Reopening Mod Settings should always open the last viewed mod page

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#158]
**Is your feature request related to a problem? Please describe.**
When you open the Mod Settings options you will always be shown the very first mod page. Or in other word the mod that is alphabetically at the first position.
But more often than now you rather want to return to the exact page that you were on last. It's way more likely that you want to readjust a setting you just worked on than you wanting to tweak the setting of the first-most mod in that list.

**Describe the solution you'd like**
When you close the Mod Settings then MSU should save the mod page you were on last.
When you open Mod Settings and a mod page was saved then this one is automatically selected.
This should at least last until the game is restarted.

**Comment by TaroEld** [comment]
Good idea, will do

**Comment by TaroEld** [comment]
Will be added in next release
