### ISSUE TITLE
[BUG] Clicking at the very top of the enum-button setting plays animation but doesn't change values

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#159]
**Versions**
 - Game: [e.g. 1.5.0.12]
 - MSU: [e.g. 1.0.5]

**Describe the bug**
When you click at the very top of an enum-button setting then this click will not be counted for the purpose of changing the value of that enum.
However the animation of the button click is still being played.

**To Reproduce**
1. Go to a settings page featuring an enum-setting
2. Click on on the middle of the enum setting: It should switch as intended
3. Now click at the top of that enum setting
3. The animation of button clicking will still play but no change is registered

**Expected behavior**
Whenever the button-click animation is played I also expect the button to be interacted with.
So either you make those clicks count as button-clicks or you remove the animation for those clicks at the top.

**Additional context**
Video showing this bug posted in Discord:
https://discord.com/channels/965324395851694140/965325468381347850/985874285866397747

*edit:* The same bug also happens when clicking at the very bottom of that button.
I also noticed there is like a 1 pixel sweetspot at the top and bottom where you can get the button to change again. But that sweetspot is surrounded by like 3 pixel "deadzone" in both directions which I talked about in this report

**Comment by Enduriel** [comment]
This is currently fixed in dev with 05b1a2b2299587a6768172e166973575d3385e7b idk why github shenanigans aren't showing that. The issue won't be closed until this is in main though.

**Comment by LordMidas** [comment]
> This is currently fixed in dev with [05b1a2b](https://github.com/MSUTeam/MSU/commit/05b1a2b2299587a6768172e166973575d3385e7b) idk why github shenanigans aren't showing that. The issue won't be closed until this is in main though.

Apparently the branch is attached to this Issue and not the PR.
