### ISSUE TITLE
[Issue] Accessing a locked setting produces a logError

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#161]
I think you should use `logWarning` or less `logInfo` to inform the user in the logs that something tries to manipulate a locked setting.
This behavior is expected to happen and not game breaking. That's why `logError` is a step too far and just confusing in the log.

![image](https://user-images.githubusercontent.com/2252464/173703566-989c01e9-9ed2-474d-b051-3dcb4f05ad38.png)

**Comment by Enduriel** [comment]
Disagree there, the modder should be checking if the setting is locked first, this shouldn't happen in practice. We're planning to add an interface to make this easier to do, but this should in fact be an error.
