### ISSUE TITLE
[REQUEST] Keybinds in .nut can currently only be used actively, not passively

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#165]
**Is your feature request related to a problem? Please describe.**
With MSU: In .nut files there seems to be no way to check the state of a keybind that you defined (whether it's held down or not) unlike in js.
This functionality is important if you want to have some code behave differently while you hold a certain key down.

MSU Keybinds allow you to combine multiple [keystates](https://github.com/MSUTeam/MSU/wiki/Keybinds#key-state), like `::MSU.Key.KeyState.Release` and `::MSU.Key.KeyState.Press`.
So theoretically I could set some variable to true and false depending on whether that keybind is pressed or not.
But there seems to be no way to know which of these states are active in the moment that the function for that keybind is called.

**Describe the solution you'd like**
Implement some sort of
`::MSU.Keybinds.isKeybindPressed(_modID, _id)` 
function

**Describe alternatives you've considered**
Pass the `_keyState` into the function call when the respective keybinds are triggered

**Comment by TaroEld** [comment]
Will be added in next release
