### ISSUE TITLE
[BUG] WeightedContainer.apply() throws error after calling setWeight

### ISSUE THREAD

**Issue by Waterplouf** [MSUTeam/MSU#183]
**Versions**
    Game: 1.5.0-12
    Legends: 16.1.2
    MSU: 1.1.1

**Describe the bug**
Script error when trying to use WeightedContainer.apply(), an error occurs as apply try to call setWeight.
Not sure why apply needs to call setWeight ?

**To Reproduce**
```          
            local mandatoryTroops = _weightedTroops.filter(@(_item, _weight) _item.Mandatory == true);
            mandatoryTroops.apply(function(_item, _weight)
            {
                for(local i = 0; i < _item.Max; i++) 
                    {
                        entities.push({
                            ID = _item.Unit.ID,
                            Script = _item.Unit.Script,
                            Variant = _item.Unit.Variant,
                            Row = _item.Unit.Row,
                            Faction = ::Const.Faction.Enemy
                        });
                    } 
                    _weightedTroops.remove(_item); // Note: error occurs with or without this line
            });
```

Where  _weightedTroops.filter(@(_item, _weight) _item.Mandatory == true) return a weightedContainer containing 1 object with weight 1.

**Expected behavior**
Apply should call function for every items in weightedContainer, that's it.

**Screenshots**

![error_WC_Apply](https://user-images.githubusercontent.com/21278366/182896036-7d0b9dee-d80f-460a-b2b6-69a08c109fb4.png)

**Log**

[log.txt](https://github.com/MSUTeam/MSU/files/9261329/log.txt)

**Additional context**

**Comment by LordMidas** [comment]
This is not a bug. The documentation of the WeightedContainer `apply` function states that the function must return the new weight for the item. If you don't want to change the weight, return the weight that is passed to the function.

**Comment by Waterplouf** [comment]
> This is not a bug. ~The documentation of the WeightedContainer `apply` function states that~ the function must return the new weight for the item. If you don't want to change the weight, return the weight that is passed to the function.
> 
> EDIT: Sorry. It seems that the documentation is missing that information. I will add the information there. EDIT 2: I have now added the information to the documentation.

Ah I see, thanks. After reading on the squirrel base array's apply function it did make more sense than the weight would/could change (since apply changes the array vs map) during apply, but I was still not understanding how to use it correctly for the weighted container.
