### ISSUE TITLE
[REQUEST] Correct the Weapontype of Nomad Sling and Staff Sling

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#210]
**Is your feature request related to a problem? Please describe.**
In Vanilla the weapons **Nomad Sling** and **Staff Sling** are categorized as **Throwing Weapon**.
![VanillaSlowingWeaponCat](https://user-images.githubusercontent.com/2252464/196928296-6f353c8f-b6a9-4d41-9c89-9844c8c9735a.PNG)

So if I use MSU then it will translate those categories into making those weapons have the **Throwing Weapon** weapontype.
This can be seen in this screenshot:
![SlingCategorizedAsThrowingWeapon](https://user-images.githubusercontent.com/2252464/196928009-68f3d850-0f26-424f-b690-93f9ae77cedc.PNG)

Why ship MSU with **Sling** as a default weapontype when it is never used in Vanilla?
After all you allow us to add new weapontypes outselves.
![WhyHaveSLingInTheFirstPlace](https://user-images.githubusercontent.com/2252464/196928742-9b003e9f-1ba5-4fa2-b4c3-f1df6b40a9d0.PNG)

**Describe the solution you'd like**
Refactor the weapontypes of **Nomad Sling** and **Staff Sling** to become **Slings** instead of **Throwing Weapons**

**Describe alternatives you've considered**
The only alternative to make this consistent would be removing **Sling** from these weapontypes. But this would break mods that previously expected this weapontype to already exist.

**Comment by LordMidas** [comment]
Sling being a default weapon type in MSU is a mistake. It shouldn't be there. By default MSU should mimic vanilla behavior, so that weapon type in MSU is redundant and should be removed.

**Comment by LordMidas** [comment]
Maybe we added Sling and Staff as default weapon types in MSU so that other people can just use these out of the box for their other sling/staff type weapons (based on my experience working on the Legends mod at that time). In any case, these can't be removed from MSU now because that would break backwards compatibility. Therefore, we'll keep them in there - but we won't change the default weapon types of any vanilla weapons.

**Comment by Enduriel** [comment]
I agree with midas and at this point will close the issue since I don't see us changing anything here
