### ISSUE TITLE
[REQUEST] onCombatStarted function for starting_scenario.nut

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#219]
**Is your feature request related to a problem? Please describe.**
Custom Origins have access to a `onCombatFinished()` function that they can overwrite but they **do not** have a `onCombatStarted ()` function that fires when any combat involving the player starts. Skills and Items do have this function.

For an Origin this function would allow us to better control and enforce certain ratios for the player composition like in the **Manhunter Origin**.
Currently the **Manhunter Origin** enforces its penalties for having too few indebted by an ugly check in the `tactical_entity_manager.nut` within the `function spawn()`.

**Describe the solution you'd like**
Add a new empty `function onCombatStarted()` in the `starting_scenario.nut` which fires once whenever a player enters combat. Basically this should fire at the same time as its Item/Skill equivalent.

**Comment by LordMidas** [comment]
Wow that ugly check you point to in vanilla is really ugly. The proposal is good, we should slate it for v1.3.0.
