### ISSUE TITLE
[BUG] onGetBackgroundTooltip for origins doesn't work under MSU

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#222]
**Versions**
 - Game: 1.5.0.12
 - MSU: 1.1.1

**Describe the bug**
The `function onGetBackgroundTooltip` for scenarios doesn't do anything while using the mod MSU

**To Reproduce**
1. Remove all mods except modding script hooks
2. Start the game, Start Manhunter origin
3. Hover over the background skill of an indebted
4. `onGetBackgroundTooltip` behavior works correctly as seen here. It adds custom lines for the background
![image](https://user-images.githubusercontent.com/2252464/199665944-e4323404-112d-42d3-8635-f10a26ebd97b.png)

5. Add **MSU** to the mods
6. Start the game, Start Manhunter origin
7. Hover over the background skill of an indebted
8. ERROR: `onGetBackgroundTooltip` behavior doesn't work correctly - the default effects are listed
![image](https://user-images.githubusercontent.com/2252464/199665699-8999eaaf-7778-445a-95f1-b291370c4152.png)

**Expected behavior**
MSU shouldn't change the behavior of existing `on ...` functions for scenarios

**Comment by Darxo** [comment]
![image](https://user-images.githubusercontent.com/2252464/199666732-ebddf46a-90ad-4144-8f62-aec397269767.png)

This bug is likely caused because you overwrite the `function general_queryStatusEffectTooltipData` (seen in the upper part of the screenshot)
But you neither call the old function nor manually add a call to the scenario in your body.

**Comment by LordMidas** [comment]
Thanks for catching this. This hook was written before the Of Flesh and Faith DLC, therefore the overwrite was functionally correct. However, with that update there were many changes to vanilla code and this was one of them. I've written a fix for this which doesn't need a complete overwrite and that will be included in v1.2.0.
