### ISSUE TITLE
[REQUEST] Re-opening the Mod Settings should return you to the last Mod/Page you were at.

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#231]
**Is your feature request related to a problem? Please describe.**
When opening the Mod Settings MSU will always display you the very first Page of the very first Mod from its data structure containing those.
This is annoying when you want to tweak a certain mod setting but you have to save and close the menu to see its impact.

But even in general it makes much more sense to return you to the last mod/page visited as it is way more likely that this is where you want to be rather than some arbitrary "first mod in the order"

**Describe the solution you'd like**
MSU should remember the last mod that you had the mod settings open of.
When you open the Mod Settings then you automatically open the settings page of that remembered mod.

MSU should also remember the exact page of that mod and select it.

**Comment by Enduriel** [comment]
@TaroEld you worked on this I'm pretty sure

**Comment by TaroEld** [comment]
Yes, it'll be in 1.2.
