### ISSUE TITLE
[BUG] getState link on Wiki page doesn't work

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#239]
**To Reproduce**
1. Go to https://github.com/MSUTeam/MSU/wiki/Utils
2. Click on getState at the top'
3. Doesn't work

**Screenshots**
![image](https://user-images.githubusercontent.com/2252464/202125453-048548b0-883a-4efc-b022-06cefd8c7582.png)

**Comment by Enduriel** [comment]
Fixed, thanks for report
