### ISSUE TITLE
[BUG] function setBaseValue has a mistake in it's inner code

### ISSUE THREAD

**Issue by IverVolgin** [MSUTeam/MSU#272]
**Versions**
 - Game: 1.5.0.12
 - MSU:  1.1.1

**Describe the bug**
While trying of implement MSU with Rebalanced Retinue Members, i trying to make a system of setting profiles, to let user save, export, import and apply different settings easily. For Vanilla settings i now trying to make a code, that will reset values of "Range settings" bars to the vanilla values, to then save values from bars. Unfortunately, the "setBaseValue" function is making an error in log and stopping the further loading of mod's code. i think it's because in code "setBaseValue" function trying to change an "this.m.BaseValue"  but "m" is never implemented in code of "range_setting.nut", "abstract_setting.nut", "settings_element.nut".

**To Reproduce**
1. install the "Mod_Rebalanced_Retinue"
2. start game, go into mods settings and see that settings page "Retinue Settings" don't load fully
3. open log file, scroll to rows after "MSU registered Rebalanced Retinue MSU, version: 3.0.0"

[Mod_Rebalanced_Retinue.zip](https://github.com/MSUTeam/MSU/files/10360511/Mod_Rebalanced_Retinue.zip)

added screenshots, excuse me, if it's just i am dumb and don't understand how things works

![2023-01-06_22-29-43](https://user-images.githubusercontent.com/63946822/211023536-ef47b994-4822-4cb8-864f-0ac43e131162.png)

![2023-01-06_22-30-31](https://user-images.githubusercontent.com/63946822/211023572-0e487c9a-72c9-40d5-8d86-8424a854ec86.png)

![2023-01-06_22-32-15](https://user-images.githubusercontent.com/63946822/211023589-1a802073-0541-4f34-8098-549dc2f73f08.png)

![2023-01-06_22-33-25](https://user-images.githubusercontent.com/63946822/211023610-5bd4fc03-6c96-4a12-aea1-9df8183eac12.png)

![2023-01-06_22-34-56](https://user-images.githubusercontent.com/63946822/211023635-b31cf59b-3d44-4d76-88a2-7e918aabc647.png)

![2023-01-06_22-36-27](https://user-images.githubusercontent.com/63946822/211023666-613d338e-67dd-4d9b-a68e-bf7954df41d4.png)

**Comment by LordMidas** [comment]
Thank you. Will fix this in 1.2.0

**Comment by IverVolgin** [comment]
> Thank you. Will fix this in 1.2.0
May i ask a question - what is the expected release date of version 1.2.0?

**Comment by LordMidas** [comment]
> > Thank you. Will fix this in 1.2.0
> May i ask a question - what is the expected release date of version 1.2.0?

Most likely early next week.

**Comment by TaroEld** [comment]
Thanks for the good report. 1.2.0 is essentially done, its in testing and if no major issues crop up, will be released early next week.

On another note, may I suggest a different organization for your mod? Right now you're queueing a new mod for each of your hooks. This is not necessary, and tends to clutter the log file. 
One organization that tends to keep things nicely separated is demonstrated here:
[Mod_Rebalanced_Retinue.zip](https://github.com/MSUTeam/MSU/files/10362263/Mod_Rebalanced_Retinue.zip)
I moved the retinue hooks to "mod_rebalanced_retinue/retinue/followers", and in the end of the !mods_preload file (which I've renamed), I 'include' the files, which tells the game to load them. This way, you can still have nice and separated files for your hooks, and you can specify the load order.

**Comment by Enduriel** [comment]
@IverVolgin probably the single best bug report I've ever seen on GitHub lol. Please find more bugs in our mods.

**Comment by IverVolgin** [comment]
> @IverVolgin probably the single best bug report I've ever seen on GitHub lol. Please find more bugs in our mods.

I'll try XD

**Comment by IverVolgin** [comment]
> Thanks for the good report. 1.2.0 is essentially done, it's in testing and if no major issues crop up, will be released early next week.
> 
> On another note, may I suggest a different organization for your mod? Right now you're queueing a new mod for each of your hooks. This is not necessary, and tends to clutter the log file. One organization that tends to keep things nicely separated is demonstrated here: [Mod_Rebalanced_Retinue.zip](https://github.com/MSUTeam/MSU/files/10362272/Mod_Rebalanced_Retinue.zip) I moved the retinue hooks to "mod_rebalanced_retinue/retinue/followers", and in the end of the !mods_preload file (which I've renamed), I 'include' the files, which tells the game to load them. This way, you can still have nice and separated files for your hooks, and you can specify the load order.

Yes, your idea is awesome and i will use it, biggest thank you! I thought that i need all this mod registrations to let another people make a compatible of their mod with my, if they will need to, but now i have a registration of mod entirely, it's "Mod_Rebalanced_Retinue_MSU" and another users can just check the installation of my mod by this row. Your tip is exellent!
