### ISSUE TITLE
[BUG] `onOtherActorDeath` should be hookLeaves

### ISSUE THREAD

**Issue by LordMidas** [MSUTeam/MSU#300]
**Versions**
 - Game: [e.g. 1.5.0.13]
 - MSU: [e.g. 1.2.2]

**Describe the bug**
`onOtherActorDeath` event is currently called via a hook on `actor.nut`. This leads to issues where when a `goblin_wolfrider` dies and spawns a wolf corpse, it doesn't call the base `onDeath` function and therefore the event doesn't run.

This event should be called via a `hookLeaves` type hook.

**Comment by Suor** [comment]
I wonder if this is causing bugs for me. I.e. a goblin or wolf not inheriting a quirk after unmounting in Standout Enemies.

**Comment by Enduriel** [comment]
We can do this in a 1.3.X release so not a priority right now but yes something it'd be good to get to.
