### ISSUE TITLE
[REQUEST] `onSetupEntity` event for entities that is called via tactical_entity_manager at the end of the `setupEntity` function

### ISSUE THREAD

**Issue by LordMidas** [MSUTeam/MSU#308]
**Is your feature request related to a problem? Please describe.**
In Reforged especially we like to add perks to entities depending on their equipment. The entities get assigned equipment during `assignRandomEquipment` and then if we have a separate event like `onSetupEntity` we can use that separate function to add perks depending on equipment.

This keeps the assignment of equipment separate from the assignment of perks, so if a submod of a mod wants to modify an entity's equipment, they don't have to copy the entire perks implementation too. They can simply overwrite the equipment function and let the main mod's perk assignment logic remain unchanged.

**Describe the solution you'd like**
Add an `onSetupEntity` event in `actor.nut` that is called at the end of the `setupEntity` funtion in tactical_entity_manager.

**Comment by Enduriel** [comment]
I'd rather have something more descriptive as a function name like afterEquipmentAssigned

**Comment by LordMidas** [comment]
> I'd rather have something more descriptive as a function name like afterEquipmentAssigned

I prefer `onSetupEntity` because it is called at the end of the `setupEntity` function, and isn't necessarily immediately after equipment assignment. The assignment of the equipment is one thing of many that happens during the `setupEntity` function. I would be happy with `afterEquipmentAssigned` if it were called directly at the end of the `assignRandomEquipment` function.

**Comment by LordMidas** [comment]
I think the `onSpawnEntity` function as proposed in #372 is probably the solution that will cover this use case as well, so we probably don't need an `onSetupEntity` or `onAfterEquipmentAssigned` functions because I have a feeling these will miss certain edge cases (e.g. resurrection) which the `onSpawnEntity` impementation properly accounts for.
