### ISSUE TITLE
[BUG] Some skills show an unnecessary damage type line

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#340]
**Versions**
 - Game: 1.5.0.15
 - MSU: 1.3.0-reforged.10

**Describe the bug**
There are certain combinations of flags in skills that cause a damage type line to show up even though those skills do not deal any direct damage or any damage at all.
I assume this happens because the skills in question ha `this.m.IsAttack = true`. They do this for targeting purposes afaik. But in their onUse they then don't call an `attackEntity` and instead apply their custom effect.

**To Reproduce**
1. Equip a fire pot
2. Hover over the description of its skill

**Expected behavior**
If these edge cases can't be predicted automatically then there should be a way to force-turn-off these damage type lines when creating our own skills. E.g. with a custom flag `this.m.HideDamageType`.

**Screenshots**
![image](https://github.com/MSUTeam/MSU/assets/2252464/84ff3902-fa4a-4753-8439-4147d3dee28d)

![image](https://github.com/MSUTeam/MSU/assets/2252464/e2e4b953-2208-4cb7-bc1a-6f555c035da5)

**Comment by LordMidas** [comment]
This has been fixed for MSU 1.3.0 via https://github.com/MSUTeam/MSU/pull/291
