### ISSUE TITLE
[REQUEST] Allow selective unsubscribing from update notifications

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#373]
### Is your feature request related to a problem? Please describe.
MSU allows authors to link their mod with a website in order to produce update notifications for a player when a newer version was released.
However not everyone wants to update to the newer version.
For example:
- Newer version breaks other mods
- Newer version is not save-game compatible
- Newer version changes balance, or adds/removes features, that the user does not agree with

### Describe the solution you'd like
- Add a mod settings page which is only visible while in the main menu and uses the persistent data storage.
- This settings page contains a boolean setting for every currently registered mods which use an update source.
- By default those settings are enabled
- A mod, that is disabled here, will no longer prompts you to visit the source for the latest version

### Need for discussion
How to treat disabled update notifications for mods which are removed?

**Team: auto-cleanup:**
- A player who at one point purposefully played an old version of a mod might have removed it later. Then one day he downloads the latest version of it as he now wants to try the latest changes. But at this point he never remembers to enable the update notification again
- A streamer who plays different modlists in parallel does not care much about the update notification of the older version of one of his mods. It is more important to him, that the other playthrough with the most recent version of the same mod actually notifies him about updates.
**Team: keep forever**
- Only thing against that ruling are players (mostly modders) who try out various different mod setups for bug testing. Once they test something with a minimal mod setup, they will wipe every setting and have to re-do those

Maybe the answer here is to introduce an additional boolean setting for **Wipe notification setting when mod not present**

**Comment by TaroEld** [comment]
I don't think we'll be touching the UX of update notifications any further, so I'll close this.
