### ISSUE TITLE
[REQUEST] Print the current day of the campaign into the log

### ISSUE THREAD

**Issue by Darxo** [MSUTeam/MSU#377]
### Is your feature request related to a problem? Please describe.
When debugging a log it can be helpful to know the current day of the playthrough to rule out certain causes or rule in new ones.

### Describe the solution you'd like
When loading a campaign, print a simple `logInfo` with the current day of the campaign.

### Describe alternatives you've considered
Additional you could print other information like difficulty at this point.

**Comment by Enduriel** [comment]
Could you make a PR for this? If so it could be merged into 1.4 with just a review
